### ISSUE TITLE
Question on the datasets

### ISSUE THREAD

**Issue by sappho192** [akpe12/JP-KR-ocr-translator-for-travel#1]
Hi,
Thank you for releasing this model :)

I'd like to rerun your `training.ipynb` in my deep learning machine but couldn't find out where the datasets are, especially `일-한 언어 corpus_train.csv` and `일-한 언어 corpus_eval.csv`.
If it's hard to share the dataset files, can you tell me the specification (Column name) of dataset csv file?
In fact, I'm trying to make my own translator which is specialized in certain Japanese game chats. So your training code can be a great reference for me.

**Comment by akpe12** [comment]
Hi, sappho192!
Thank you for using my model.

I just uploaded dataset in Kaggle, so you can find the related link in my readme.md :)
I hope your project will be completed successfully.

**Comment by sappho192** [comment]
@akpe12 Thank you for the response :)

> I just uploaded dataset in Kaggle, so you can find the related link in my readme.md :) I hope your project will be completed successfully.

However, I can't access your dataset with provided link. Can you check if the dataset is uploaded as private or else?

**Comment by akpe12** [comment]
@sappho192 I just changed the setting! Thank you for letting me know.

**Comment by sappho192** [comment]
Now I can access the dataset! Thank you 😉
